### ISSUE TITLE
Use multiple observations to find valid values

### ISSUE THREAD

**Issue by MatthewFlamm** [MatthewFlamm/pynws#15]
In simple API, use multiple observations over some time period (1 hr?) in case only partial updates are provided by station.

**Comment by rewsssiestedbo** [comment]
What might be a better approach is to include an optional parameter to specify the time to start retrieving the observations.  This would allow the caller to keep track of the last observation it received and request the update to cover the time period since that last observation.

**Comment by MatthewFlamm** [comment]
What I'm imagining is to request the last x observations, use the latest valid value for each quantity within some time period y.  Does this work?  Your approach probably requests less data and is more configurable, but has more logic required here and in the user code.

**Comment by rewsssiestedbo** [comment]
I'm not sure why using a start time instead of a count would be more complicated.  The NWS API allows for specifying the start time (and end time) for the observations being requested.  My experience with using just a specific count is that you may or may not get valid measurements for all parameters:  during times when wind speed or direction is changing frequently, there may be 5-10 observations in an hour, while at other times you just get one complete observation each hour.

**Comment by MatthewFlamm** [comment]
I agree that it is easy to specify the time period, this is better than number of observations.
